import './globals.css'
import { Inter } from 'next/font/google'
import { Montserrat } from 'next/font/google'
import Navbar from '@/components/navbar/page'
import localFont from 'next/font/local'


const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className={` scroll-smooth `} lang="en">
     
      <body className={`${montserrat.className} `}>{children}</body>
    </html>
  )
}
